api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    doctrine:
        # To enable or disable Doctrine ORM support.
        enabled: true
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
