nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type','CONTENT_TYPE', 'Authorization', 'Access-Control-Allow-Origin','HTTP_X-AUTH-TOKEN','HTTP_ACCEPT']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
